name: CI

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets: inherit
