# Dispatches a full publish workflow whenever a PR that has been merged and
# has the 'release-candidate' label is closed.
name: Dispatch Publish

on:
  pull_request:
    types:
      - closed
  push:
      branches:
        - test-edits
        - non-existent-branch

jobs:
  publish:
    # if: contains(github.event.pull_request.labels.*.name, 'release-candidate') && github.event.pull_request.merged == true
    if: always()
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch - Test
        run: |
          # Set the required variables
          repo_owner="embrace-io"
          repo_name="embrace-unity-sdk-internal"  
          event_type="test-sdk" 

          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.PUBLIC_SDK_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
          -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"unit\": false, \"integration\": true}}"
