name: Test PR

on:
  pull_request:

jobs:
  TestSDK:
    name: Test SDK
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch - Test
        run: |
          # Set the required variables
          repo_owner="embrace-io"
          repo_name="embrace-unity-sdk-internal"  
          event_type="test-sdk" 

          echo "Dispatching the $event_type event to $repo_owner/$repo_name"

          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.PUBLIC_SDK_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
          -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"unit\": false, \"integration\": true}}"