name: Update Embrace iOS Dependency

on:
  workflow_dispatch:
  push:
    branches:
      - alyssa/iOS-upgrade-6.4.2

jobs:
  update-iOS-dependency:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Public SDK
        uses: actions/checkout@v4
      
      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
      - name: Get latest iOS SDK release via GH
        id: get_release
        run: |
          gh release list --repo embrace-io/embrace-apple-sdk --limit 1 --json tagName,isLatest --jq '.[] | {tag: .tagName, isLatest: .isLatest}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Print Release Info
        run: |
          echo "Release Info: ${{ steps.get_release.outputs }}"
      - name: Install xcpretty
        run: sudo gem install xcpretty
      - name: Download Latest iOS SDK Release
        run: |
          gh release download --repo embrace-io/embrace-apple-sdk --pattern 'embrace_*.zip' --dir ./latest_iOS/
      - name: Echo Latest iOS SDK Release
        run: |
          ls -l ./latest_iOS/
      # - name: Update Embrace iOS Dependency
      #   run: |
      #     echo "Updating Embrace iOS Dependency"
      #     cd public_sdk
      #     ./scripts/update_ios_dependency.sh
      #     env:
      #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}