name: Update Embrace iOS Dependency

on:
  workflow_dispatch:
  push:
    branches:
      - alyssa/iOS-upgrade-6.4.2

jobs:
  update-iOS-dependency:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Public SDK
        uses: actions/checkout@v4
      - name: Install xcpretty
        run: sudo gem install xcpretty
      # - name: Get latest iOS SDK release via GH
      #   run: |
      #     curl -L -O
      - name: Install GitHub CLI
        run: sudo apt-get install gh -y
      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
      - name: Get latest iOS SDK release via GH
        id: get_release
        run: |
          gh release list --repo embrace-io/embrace-apple-sdk --limit 1 --json tagName,name,body,assets --jq '.[] | {tag: .tagName, name: .name, body: .body, assets: .assets}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Print Release Info
        run: |
          echo "Release Info: ${{ steps.get_release.outputs }}"
      # - name: Update Embrace iOS Dependency
      #   run: |
      #     echo "Updating Embrace iOS Dependency"
      #     cd public_sdk
      #     ./scripts/update_ios_dependency.sh
      #     env:
      #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}